# yaml-language-server: $schema=https://coderabbit.ai/integrations/schema.v2.json
language: en-US
tone_instructions: 'You are an expert code reviewer in TypeScript, JavaScript, and NodeJS. You work in an enterprise software developer team, providing concise and clear code review advice. Only elaborate when asked.'
early_access: true
enable_free_tier: true
inheritance: false
reviews:
  profile: chill
  request_changes_workflow: true
  high_level_summary: true
  high_level_summary_instructions: 'This is a React + TypeScript vinyl record collection app using TanStack Router/Query, shadcn/ui, and Tailwind CSS. Focus summaries on user-facing changes and architectural impacts.'
  high_level_summary_placeholder: '@coderabbitai summary'
  high_level_summary_in_walkthrough: true
  auto_title_placeholder: '@coderabbitai'
  auto_title_instructions: "Format: '<type>: <description>'. Type must be: feat, fix, docs, style, refactor, perf, test, build, ci, chore. Keep under 72 chars."
  review_status: true
  review_details: true
  commit_status: true
  fail_commit_status: false
  collapse_walkthrough: false
  changed_files_summary: true
  sequence_diagrams: false
  estimate_code_review_effort: true
  assess_linked_issues: true
  related_issues: true
  related_prs: true
  suggested_labels: true
  labeling_instructions:
    - label: 'type: feature'
      instructions: 'Apply when PR adds new functionality or capabilities'
    - label: 'type: bug'
      instructions: 'Apply when PR fixes a bug or incorrect behavior'
    - label: 'type: chore'
      instructions: 'Apply for maintenance tasks like dependency updates, config changes, or refactoring'
    - label: 'area: ui'
      instructions: 'Apply when PR changes components, styling, or user interface'
    - label: 'area: api'
      instructions: 'Apply when PR modifies API layer, client, or data fetching'
  auto_apply_labels: true
  suggested_reviewers: true
  auto_assign_reviewers: true
  in_progress_fortune: false
  poem: false
  enable_prompt_for_ai_agents: true
  path_filters:
    - '!dist/**'
    - '!build/**'
    - '!coverage/**'
    - '!**/__generated__/**'
    - '!**/generated/**'
    - '!*.lock'
    - '!bun.lockb'
    - '!pnpm-lock.yaml'
    - '!package-lock.json'
    - '!**/*.{png,jpg,jpeg,gif,svg,ico,webp}'
    - '!**/*.xml'
  path_instructions:
    - path: 'src/**/*.{ts,tsx}'
      instructions: >-
        Review TypeScript and React code for conformity with best practices.
        Check: proper hook usage (dependency arrays in useEffect/useMemo/useCallback),
        accessibility (a11y), avoid `any` types (prefer `unknown`), explicit return types
        on exported functions, proper error handling, and component composition patterns.
        Ensure internationalization strings are externalized (i18next).
    - path: 'vite.config.ts'
      instructions: >-
        Review PWA config changes: manifest details, workbox caching strategies,
        runtime caching TTLs, and that assets fall under intended caches.
        Ensure import.meta.env usage is correct and no secrets are bundled.
    - path: 'src/**'
      instructions: >-
        For PWA-related changes, check offline behavior, error states, and that
        network-first/cache-first choices align with product expectations.
    - path: 'src/api/**/*.ts'
      instructions: >-
        Review API code for proper error handling, rate limiting compliance,
        and secure credential handling. Ensure API responses are properly typed.
    - path: 'src/hooks/**/*.ts'
      instructions: >-
        Review custom hooks for correct dependency arrays, proper cleanup
        in effects, and clear return type signatures.
  abort_on_close: true
  disable_cache: false
  auto_review:
    enabled: true
    auto_incremental_review: true
    ignore_title_keywords:
      - 'WIP'
      - 'DO NOT MERGE'
    labels: []
    drafts: false
    base_branches:
      - main
    ignore_usernames: []
  finishing_touches:
    docstrings:
      enabled: true
    unit_tests:
      enabled: false
  pre_merge_checks:
    docstrings:
      mode: warning
      threshold: 80
    title:
      mode: warning
      requirements: '^(feat|fix|docs|style|refactor|perf|test|build|ci|chore)(\\([^)]+\\))?: .{1,72}$'
    description:
      mode: warning
    issue_assessment:
      mode: warning
    custom_checks:
      - name: 'Type Safety'
        instructions: 'Verify no `any` types are introduced without justification. Check that exported functions have explicit return types.'
        mode: warning
      - name: 'Debug Statements'
        instructions: 'Ensure no console.log/debugger statements are left in production code. console.warn/error are OK when justified.'
        mode: warning
  tools:
    ast-grep:
      rule_dirs: []
      util_dirs: []
      essential_rules: true
      packages: []
    shellcheck:
      enabled: true
    ruff:
      enabled: true
    markdownlint:
      enabled: true
    github-checks:
      enabled: true
      timeout_ms: 90000
    languagetool:
      enabled: true
      enabled_rules: []
      disabled_rules: []
      enabled_categories: []
      disabled_categories: []
      enabled_only: false
      level: default
    biome:
      enabled: true
    hadolint:
      enabled: true
    swiftlint:
      enabled: true
    phpstan:
      enabled: true
      level: default
    phpmd:
      enabled: true
    phpcs:
      enabled: true
    golangci-lint:
      enabled: true
    yamllint:
      enabled: true
    gitleaks:
      enabled: true
    checkov:
      enabled: true
    detekt:
      enabled: true
    eslint:
      enabled: true
    flake8:
      enabled: true
    fortitudeLint:
      enabled: true
    rubocop:
      enabled: true
    buf:
      enabled: true
    regal:
      enabled: true
    actionlint:
      enabled: true
    pmd:
      enabled: true
    clang:
      enabled: true
    cppcheck:
      enabled: true
    semgrep:
      enabled: true
    circleci:
      enabled: true
    clippy:
      enabled: true
    sqlfluff:
      enabled: true
    prismaLint:
      enabled: true
    pylint:
      enabled: true
    oxc:
      enabled: true
    shopifyThemeCheck:
      enabled: true
    luacheck:
      enabled: true
    brakeman:
      enabled: true
    dotenvLint:
      enabled: true
    htmlhint:
      enabled: true
    checkmake:
      enabled: true
    osvScanner:
      enabled: true
chat:
  art: true
  auto_reply: true
  integrations:
    jira:
      usage: auto
    linear:
      usage: auto
knowledge_base:
  opt_out: false
  web_search:
    enabled: true
  code_guidelines:
    enabled: true
    filePatterns:
      - 'AGENTS.md'
  learnings:
    scope: auto
  issues:
    scope: auto
  jira:
    usage: auto
    project_keys: []
  linear:
    usage: auto
    team_keys: []
  pull_requests:
    scope: auto
  mcp:
    usage: auto
    disabled_servers: []
code_generation:
  docstrings:
    language: en-US
    path_instructions:
      - path: 'src/**/*.ts'
        instructions: 'Use TSDoc format with @param, @returns, and @example tags where helpful. Keep descriptions concise.'
      - path: 'src/**/*.tsx'
        instructions: 'Use TSDoc format. Document component props with @param, include @example for complex components.'
issue_enrichment:
  auto_enrich:
    enabled: true
  planning:
    enabled: true
    auto_planning:
      enabled: true
      labels: []
  labeling:
    labeling_instructions:
      - label: 'type: feature'
        instructions: 'Apply when issue requests new functionality'
      - label: 'type: bug'
        instructions: 'Apply when issue reports a bug or incorrect behavior'
      - label: 'area: ui'
        instructions: 'Apply when issue relates to components, styling, or user interface'
      - label: 'area: api'
        instructions: 'Apply when issue relates to API layer or data fetching'
    auto_apply_labels: true
